{{- if .Values.brinekey.githubRemotePath }}
apiVersion: brinekey.brinecrypt.io/v1alpha1
kind: BrinecryptSecret
metadata:
  name: {{ .Values.brinekey.targetSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coralforge.labels" . | nindent 4 }}
spec:
  remotePath: {{ .Values.brinekey.githubRemotePath | quote }}
  serviceAccount: {{ include "coralforge.serviceAccountName" . }}
  targetSecret: {{ .Values.brinekey.targetSecret | quote }}
  secretKey: {{ .Values.brinekey.secretKey | quote }}
  refreshInterval: {{ .Values.brinekey.refreshInterval | quote }}
{{- end }}
