kind: pipeline
type: docker
name: bm25-ci

trigger:
  branch:
    include:
      - main
      - release/*

steps:
  - name: configure
    image: python:3.12-slim
    commands:
      - python -m pip install -r requirements.txt
  - name: build
    image: python:3.12-slim
    commands:
      - python -m build
  - name: test
    image: python:3.12-slim
    commands:
      - python -m pytest
  - name: lint
    image: python:3.12-slim
    commands:
      - python -m ruff check .
