brinecrypt:
  url: "http://brinecrypt.kube-ex.svc.cluster.local:8080"

github:
  repo: "RazzorCodes/brinecrypt"

brinekey:
  githubRemotePath: "github/coralforge-brinecrypt-repo-contents-rw-pat"

repos:
  - owner: RazzorCodes
    repo: brinecrypt
    tokenSecretRef:
      namespace: github
      name: coralforge-brinecrypt-repo-contents-rw-pat
      key: github_token
  - owner: RazzorCodes
    repo: bm25lib
    tokenSecretRef:
      namespace: github
      name: coralforge-bm25-pat
      key: github_token
